apiVersion: skaffold/v2beta7
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: habuma/books
    buildpacks:
      builder: gcr.io/paketo-buildpacks/builder:base-platform-api-latest
      dependencies:
        paths:
        - src/main
        - pom.xml
metadata:
  name: books-k-s
deploy:
  kubectl:
    manifests:
    - src/main/k8s/deploy.yaml