apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfjs-books-k8s-deploy
  labels:
    app: spring-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-k8s
  template:
    metadata:
      labels:
        app: spring-k8s
    spec:
      containers:
      - name: nfjs-books-k8s-container
        image: habuma/nfjs-books:latest
---
apiVersion: v1
kind: Service
metadata:
  name: nfjs-books-svc
  labels:
    app: spring-k8s
spec:
  type: NodePort
  ports:
  - port: 31234
    nodePort: 30123
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: spring-k8s
