apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: hello-k-s
build:
  artifacts:
  - image: habuma/hello-k8s
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
#      trustBuilder: true
deploy:
  kubectl:
    manifests:
    - k8s/deploy.yaml
