greeting:
  message: Hello Des Moines!
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
  endpoint:
    health:
      show-details: always
           
info:
  contact:
    phone: 123-123-1234