greeting:
  who: workshop attendees
  
management:
  endpoint:
    health:
      show-details: always
      
  endpoints:
    web:
      exposure:
        include: '*'
        
info:
  contact:
    phone: 123-123-1234
    email: support@example.com
    fax: 321-321-3210