services:
  qdrant:
    image: 'qdrant/qdrant:latest'
    ports:
      - '6334:6334'
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus-config.yml:/etc/prometheus/prometheus.yml"
    networks:
      - grafana-network
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - grafana-network
networks:
  grafana-network:
    driver: bridge
volumes:
  grafana-storage: {}

