server:
  port: 9090

greeting:
  message: Hello World!
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
  
  endpoint:
    health:
      show-details: always

info:
  contact:
    phone: 123-123-1234
    email: support@example.com
  
---
spring:
  profiles: boston
  
greeting:
  message: Hello Boston!
---
spring:
  profiles: denver
  
greeting:
  message: Hello Denver!
