spring:
  application:
    name: NFJS-Books
  boot:
    admin:
      client:
        url: http://localhost:9999

server:
  port: 8080

info:
  support:
    phone: 123-123-1234
    email: support@example.com
  fax: 321-321-3214
  app-name: ${spring.application.name}
  
management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
      
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: heapdump
        