apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-k8s-deploy
  labels:
    app: spring-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-k8s
  template:
    metadata:
      labels:
        app: spring-k8s
    spec:
      containers:
      - name: books-k8s-container
        image: habuma/books:latest
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        readinessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /actuator/health/readiness
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: books-svc
  labels:
    app: spring-k8s
spec:
  type: NodePort
  ports:
  - port: 31234
    nodePort: 30123
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: spring-k8s
