apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s-deploy
  labels:
    app: spring-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-k8s
  template:
    metadata:
      labels:
        app: spring-k8s
    spec:
      containers:
      - name: hello-k8s-container
        image: habuma/hello-archconf:latest
        env:
        - name: SPRING_CONFIG_IMPORT
          value: /etc/config/
        volumeMounts:
        - name: hello-config
          mountPath: /etc/config
      volumes:
      - name: hello-config
        configMap:
          name: hello-config
          items:
          - key: application.properties
            path: application.properties
          - key: application.yml
            path: application.yml
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: spring-k8s
spec:
  type: NodePort
  ports:
  - port: 31234
    nodePort: 30123
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: spring-k8s
