spring:
  application:
    name: hello-service

server:
  shutdown: graceful
  
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
        
  endpoints:
    web:
      exposure:
        include: '*'
        