apiVersion: v1
kind: Service
metadata:
  name: k8s-workshop
  labels:
    app: k8s-workshop
spec:
  type: NodePort
  ports:
  - port: 31234
    nodePort: 30123
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: k8s-workshop
