greeting:
  message: Hello UberConf!
  
management:
  endpoint:
    health:
      show-details: always
      
  endpoints:
    web:
      exposure:
        include: '*'
        
info:
  contact:
    email: support@example.com
    phone: 123-123-1234
        