
spring:
  cloud:
    stream:
      bindings:
        solve-in-0:
          destination: equations
          group: quadratic
        solve-out-0:
          destination: solutions
          group: quadratic